main: ${project.main}
author: ${project.authors}
version: ${project.version}
name: ${project.name}

commands:
  scribe reload:
    description: Reload Scribe config file.
    permission: scribe.admin

permissions:
  scribe.use:
    description: Allows usage of Scribe
    default: op
  scribe.admin:
    description: Allows reloading Scribe's config file.
    default: op
